;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Monster.Event.Dead",NewTagName="Monster.State.Dead")
+GameplayTagRedirects=(OldTagName="Monster.Event",NewTagName="Monster.State")
+GameplayTagList=(Tag="Monster.Event.TriggerOverlap",DevComment="")
+GameplayTagList=(Tag="Monster.Event.WakeUp",DevComment="")
+GameplayTagList=(Tag="Monster.State.Dead",DevComment="")
+GameplayTagList=(Tag="Monster.State.Patrol",DevComment="")
+GameplayTagList=(Tag="Monster.State.Statue",DevComment="")

